apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-hello
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-hello
  source:
    repoURL: https://github.com/sanket363/nodejs-helloWorldApp-on-K8s.git
    path: nodjs-hello/
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

