apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000

