name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Set image tag
        id: tag
        run: echo "::set-output name=TAG::v${{ github.run_number }}"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag snaket2628/nodejs-app:latest

      - name: Docker Push
        run: docker push snaket2628/nodejs-app:latest
